spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: fine-service-route
              uri: lb://fine-service
              predicates:
                - Path=/api/v1/fines/**
            - id: reservation-service-route
              uri: lb://reservation-service
              predicates:
                - Path=/api/v1/reservations/**
            - id: user-service-route
              uri: lb://user-service
              predicates:
                - Path=/api/v1/users/**

server:
  port: 8888

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true