eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reservation-service_db
    username: postgres
    password: reservation_db_password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    format-sql: true

  kafka:
    bootstrap-servers: localhost:9094
  cloud:
    stream:
      kafka:
        binders:
          brokers: localhost:9094
      bindings:
        reservationCreated-out-0:     #dışarıya bir mesaj gönderir
          destination: reservation-topic
          contentType: application/json  #mesaj içeriğini serialize ederken json kullan

        loanReturnedEvent-in-0:
          destination: loan-topic
          group: reservation-service
          contentType: application/json

        bookCopyAddedEvent-in-0:
          destination: book-topic
          group: reservation-service
          contentType: application/json
