eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/fine_service_db
    username: postgres
    password: fine_db_password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    format-sql: true

  kafka:
    bootstrap-servers: localhost:9094

  cloud:
    stream:
      kafka:
        binders:
          brokers: localhost:9094
      bindings:
        fineCreated-out-0:
          destination: fine-topic
          contentType: application/json

        loanOverdueEvent-in-0:
          destination: loan-events
          group: fine-service
