spring:
  cloud:
    stream:
      default-binder: kafka
      bindings:
        loan-events-out-0:
          destination: loan-events          # Kafka topic adı
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9094
          auto-create-topics: true

  datasource:
    url: jdbc:postgresql://localhost:5435/loandb
    username: postgres
    password: loan
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/